Update 1-install_nginx_web_server

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,13 +1,33 @@
 #!/usr/bin/env bash
-# Install and configure nginx
-# to return 'Hello World!' on a GET request
-# to /
+#install ngix and have a file that returns the string "Hello World  inside
 
-function install_and_configure_nginx(){
-    sudo apt-get update
-    sudo apt-get -y install nginx
-    echo 'Hello World!' > /var/www/html/index.html
-    service nginx start
-
+sudo apt-get update -y && \
+sudo apt-get install -y nginx
+if [ $? -eq 0 ]
+then
+    echo -e \
+"http {
+    root /var/www/school;
+    index index.html;
+    server {
+        listen 80;
+        location \ {
+        }
+    }
 }
-install_and_configure_nginx;
+events {
+}" > /etc/nginx/nginx.conf
+    mkdir -p /var/www/school
+    echo "Hello World!" > \
+	/var/www/school/index.html
+    service nginx start
+    if [ $? -ne 0 ]
+    then
+	"Problem starting nginx"
+	exit 1
+    fi
+else
+    echo "Could not install nginx"
+    exit 1
+fi
+exit 0
